#include<iostream>
using namespace std;
main()
{
int a;
int b;
int c;
int d;
int e;
int f;
int g;
int h;
int i;
int j;
int k;
int l;
int m;
int n;
int o;
int add;
int mul;
int sub;
int result;
cout<<"enter first number"<<endl;
cin>>a;
cout<<"enter second  number"<<endl;
cin>>b;
cout<<"enter third  number"<<endl;
cin>>c;
cout<<"enter fourth  number"<<endl;
cin>>d;
cout<<"enter fifth  number"<<endl;
cin>>e;
cout<<"enter sixth  number"<<endl;
cin>>f;
cout<<"enter seventh  number"<<endl;
cin>>g;
cout<<"enter eighth  number"<<endl;
cin>>h;
cout<<"enter ninth  number"<<endl;
cin>>i;
cout<<"enter tenth  number"<<endl;
cin>>j;
cout<<"enter eleventh number"<<endl;
cin>>k;
cout<<"enter twelveth  number"<<endl;
cin>>l;
cout<<"enter thirteenth  number"<<endl;
cin>>m;
cout<<"enter fourteenth  number"<<endl;
cin>>n;
cout<<"enter fifteenth  number"<<endl;
cin>>o;
sum=a+b+c+d+e;
mul=f*g*h*i*j;
sub=k-l-m-n-o;
result=(sum+mul)-sub;
cout<<"result is "<<result<<endl;
}

